import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Pencil, Save, Trash2, UserRound, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { LocationFields } from '../../components/LocationFields.jsx';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { DashboardTabs, Pagination } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate, humanize } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

const emptyEditValues = { fullName: '', country: 'India', city: '', state: '', businessName: '', status: 'active', reason: '' };

export function AdminUserDetailPage() {
  const { id } = useParams(); const navigate=useNavigate(); const queryClient=useQueryClient(); const [active, setActive] = useState('account'); const [removeReason,setRemoveReason]=useState(''); const [code,setCode]=useState(''); const [codeReason,setCodeReason]=useState(''); const [referralPage,setReferralPage]=useState(1);
  const detail = useQuery({ queryKey: ['admin-user', id], queryFn: async () => (await api.get(`/dashboard/admin/users/${id}`)).data.data });
  const editForm=useForm({defaultValues:emptyEditValues});
  useEffect(()=>{if(detail.data)editForm.reset(editValues(detail.data))},[detail.data,editForm]);
  const update=useMutation({mutationFn:(values)=>api.patch(`/dashboard/admin/users/${id}`,values),onSuccess:()=>Promise.all([queryClient.invalidateQueries({queryKey:['admin-user',id]}),queryClient.invalidateQueries({queryKey:['admin-users']}),queryClient.invalidateQueries({queryKey:['dashboard','admin']})])});
  const updateCode=useMutation({mutationFn:()=>api.patch(`/dashboard/admin/connectors/${id}/referral-code`,{referralCode:code,reason:codeReason}),onSuccess:()=>{setCode('');setCodeReason('');return Promise.all([queryClient.invalidateQueries({queryKey:['admin-user',id]}),queryClient.invalidateQueries({queryKey:['admin-users']})])}});
  const remove=useMutation({mutationFn:()=>api.delete(`/dashboard/admin/users/${id}`,{data:{reason:removeReason}}),onSuccess:()=>{queryClient.removeQueries({queryKey:['admin-user',id]});queryClient.invalidateQueries({queryKey:['admin-users']});queryClient.invalidateQueries({queryKey:['dashboard','admin']});navigate(`/admin/dashboard?section=${accountType(detail.data)==='contractor'?'contractors':'customers'}`,{replace:true})}});
  if (detail.isLoading) return <div className="shell route-loading">Loading user details…</div>;
  if (detail.isError) return <div className="shell route-loading"><h1>User unavailable</h1><p>{apiMessage(detail.error)}</p></div>;
  const { user, profile, metrics, referredUsers } = detail.data; const type=accountType(detail.data); const directory=type==='contractor'?'contractors':'customers'; const typeLabel=humanize(type); const directoryLabel=type==='contractor'?'connectors':'customers';
  const tabs = [{ id: 'account', label: 'Full details', icon: UserRound }, { id: 'manage', label: 'Manage account', icon: Pencil }, ...(type==='contractor' ? [{ id: 'registrations', label: 'Referred customers', icon: Users, count: metrics.approvedReferrals }] : [])];
  function confirmRemoval(){if(removeReason.trim().length<3)return;if(window.confirm(`Remove ${user.fullName}'s portal access? Their applications, referrals, and audit history will be preserved.`))remove.mutate()}
  return <DashboardShell role="admin" title={user.fullName}><Link className="inline-link" to={`/admin/dashboard?section=${directory}`}>← Back to {directoryLabel}</Link><section className="dashboard-welcome"><div><span className="eyebrow">{typeLabel} details</span><h1>{user.fullName}</h1><p>{user.email||'No email'} · {user.mobile} · {humanize(user.status)}</p></div>{type==='contractor' && user.referralCode && <div className="referral-code-card"><span>Referral code</span><strong>{user.referralCode}</strong></div>}</section>{type==='contractor' && <section className="metric-grid"><Metric label="Total approved referrals" value={metrics.approvedReferrals}/></section>}<DashboardTabs tabs={tabs} active={active} onChange={setActive} label="User detail sections"/>
    {active === 'account' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="card-heading"><div><span className="eyebrow">Registered information</span><h2>Account and profile details</h2><p>Login identifiers and user-owned activity are displayed read-only.</p></div><UserRound/></div><dl className="detail-list admin-account-details"><Detail label="Account type" value={humanize(type)}/><Detail label={`${humanize(type)} ID`} value={profile?.contractorId||profile?.customerId||'—'}/><Detail label="Full name" value={user.fullName}/>{type==='contractor'&&<Detail label="Business name" value={profile?.businessName||'—'}/>}<Detail label="Email" value={user.email||'—'}/><Detail label="Phone" value={user.mobile}/><Detail label="Country" value={profile?.country||'India'}/><Detail label="State" value={profile?.state||'—'}/><Detail label="City" value={profile?.city||'—'}/><Detail label="Account status" value={humanize(user.status)}/>{type==='contractor'&&<Detail label="Onboarding status" value={profile?.onboardingStatus?humanize(profile.onboardingStatus):'—'}/>} {type==='contractor'&&<Detail label="Referral code" value={user.referralCode||'Generated after first sign-in'}/>}<Detail label="Registered" value={formatDate(user.createdAt)}/><Detail label="First login" value={formatDate(user.firstLoginAt)}/></dl></section>}
    {active === 'account' && type === 'customer' && <section className="dashboard-card dashboard-section"><h2>Customer classification</h2><dl className="detail-list"><Detail label="Customer type" value={profile?.customerType === 'nri' ? 'NRI Customer' : 'Indian Customer'}/><Detail label="Referral approval status" value={humanize(profile?.referralApprovalStatus || 'none')}/><Detail label="Connector code submitted" value={profile?.referralCodeSubmitted || 'None'}/></dl></section>}
    {active === 'manage' && <div className="dashboard-columns tab-panel user-management-grid" role="tabpanel"><section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Limited profile correction</span><h2>Edit allowed fields</h2><p>Email, mobile, referral code, applications, service referrals, and login history cannot be edited here.</p></div><Pencil/></div><form className="dashboard-form" onSubmit={editForm.handleSubmit((values)=>update.mutate(values))}><div className="form-grid"><Field label="Full name" register={editForm.register('fullName',{required:'Enter the full name',minLength:{value:2,message:'Enter at least 2 characters'}})} error={editForm.formState.errors.fullName}/>{type==='contractor'&&<Field label="Business name" register={editForm.register('businessName')}/>}<LocationFields form={editForm}/><label>Portal access<select {...editForm.register('status')}><option value="active">Active</option><option value="suspended">Suspended</option></select></label></div><label>Reason for change<textarea rows="3" {...editForm.register('reason',{required:'Enter a reason for this administrative change',minLength:{value:3,message:'Enter at least 3 characters'}})}/>{editForm.formState.errors.reason&&<small className="field-error" role="alert">{editForm.formState.errors.reason.message}</small>}</label>{update.isError&&<p className="form-error">{apiMessage(update.error)}</p>}{update.isSuccess&&<p className="form-success">Account changes saved and recorded in the audit log.</p>}<button className="button button-gold" disabled={update.isPending}><Save size={17}/>{update.isPending?'Saving…':'Save allowed changes'}</button></form></section><section className="dashboard-card dashboard-section danger-zone"><div className="card-heading"><div><span className="eyebrow">Account removal</span><h2>Remove portal access</h2></div><Trash2/></div><p>This blocks sign-in and removes the person from admin directories. Financial applications, referrals, and audit history remain preserved and cannot be edited through this action.</p><label>Required removal reason<textarea rows="4" value={removeReason} onChange={(event)=>setRemoveReason(event.target.value)} placeholder="Why is this account being removed?"/></label>{remove.isError&&<p className="form-error">{apiMessage(remove.error)}</p>}<button type="button" className="button danger-button" disabled={remove.isPending||removeReason.trim().length<3} onClick={confirmRemoval}><Trash2 size={17}/>{remove.isPending?'Removing access…':'Remove account access'}</button></section></div>}
    {active === 'manage' && type === 'contractor' && <section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Admin-only setting</span><h2>Change referral code</h2><p>Existing referral records keep their historical code.</p></div></div><form className="dashboard-form" onSubmit={(event)=>{event.preventDefault();updateCode.mutate()}}><label>New referral code<input value={code} onChange={(event)=>setCode(event.target.value.toUpperCase())} placeholder="CONN-8XJ4K2"/></label><label>Reason<textarea value={codeReason} onChange={(event)=>setCodeReason(event.target.value)} rows="3"/></label>{updateCode.isError&&<p className="form-error">{apiMessage(updateCode.error)}</p>}{updateCode.isSuccess&&<p className="form-success">Referral code updated.</p>}<button className="button button-gold" disabled={updateCode.isPending||code.length<11||codeReason.trim().length<3}><Save size={17}/>Update referral code</button></form></section>}
    {active === 'registrations' && type==='contractor' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><h2>Customers referred by this connector</h2><ResponsiveTable columns={['Name', 'Email', 'Phone', 'Account', 'Status', 'Decision date']} rows={referredUsers.slice((referralPage-1)*8,referralPage*8).map((item) => [item.fullName, item.email || '—', item.mobile, item.accountCreated ? 'Created' : 'Not created', humanize(item.referralStatus), item.approvedAt || item.rejectedAt ? formatDate(item.approvedAt || item.rejectedAt) : 'Awaiting Admin'])} empty="No customer referrals have been submitted."/><Pagination page={referralPage} pages={Math.ceil(referredUsers.length/8)} total={referredUsers.length} onChange={setReferralPage} label="customer referrals"/></section>}
  </DashboardShell>;
}

function accountType(data){return data?.user?.roles?.some((role)=>role.slug==='contractor')?'contractor':'customer'}
function editValues(data){return {fullName:data.user.fullName||'',country:data.profile?.country||'India',city:data.profile?.city||'',state:data.profile?.state||'',businessName:data.profile?.businessName||'',status:['active','suspended'].includes(data.user.status)?data.user.status:'suspended',reason:''}}
function Detail({label,value}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function Metric({ label, value }) { return <article className="metric-card compact"><span>{label}</span><strong>{value}</strong></article>; }
function Field({label,register,error}){return <label>{label}<input aria-invalid={Boolean(error)} {...register}/>{error&&<small className="field-error" role="alert">{error.message}</small>}</label>}
