import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Pencil, Plus, Scale, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { Pagination } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

export function AdminLegalServicesPage() {
  const queryClient = useQueryClient(); const [name, setName] = useState(''); const [editing, setEditing] = useState(null); const [servicePage,setServicePage]=useState(1); const [requestPage,setRequestPage]=useState(1);
  const services = useQuery({ queryKey: ['admin-legal-services'], queryFn: async () => (await api.get('/legal-services/admin/services')).data.data });
  const requests = useQuery({ queryKey: ['admin-legal-requests'], queryFn: async () => (await api.get('/legal-services/admin/requests')).data.data });
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ['admin-legal-services'] }), queryClient.invalidateQueries({ queryKey: ['legal-services'] })]);
  const save = useMutation({ mutationFn: () => editing ? api.patch(`/legal-services/admin/services/${editing._id}`, { name, active: editing.active }) : api.post('/legal-services/admin/services', { name, active: true }), onSuccess: () => { setName(''); setEditing(null); return refresh(); } });
  const remove = useMutation({ mutationFn: (id) => api.delete(`/legal-services/admin/services/${id}`), onSuccess: refresh });
  function edit(item) { setEditing(item); setName(item.name); }
  const serviceItems=services.data||[]; const requestItems=requests.data||[]; const servicePages=Math.max(1,Math.ceil(serviceItems.length/8)); const requestPages=Math.max(1,Math.ceil(requestItems.length/8));
  return <DashboardShell role="admin" title="Legal Services"><header className="admin-page-heading"><span className="eyebrow">Admin dashboard</span><h1>Legal Services</h1><p>Manage the choices shown in the customer legal service form.</p></header><section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Service catalogue</span><h2>{editing ? 'Edit service' : 'Add service'}</h2></div><Scale/></div><form className="dashboard-form" onSubmit={(event) => { event.preventDefault(); if (name.trim().length >= 2) save.mutate(); }}><label>Service name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Example: Lawyer"/></label><div className="button-row"><button className="button button-gold" disabled={save.isPending || name.trim().length < 2}>{editing ? <Pencil size={17}/> : <Plus size={17}/>} {editing ? 'Save changes' : 'Add service'}</button>{editing && <button type="button" className="button button-outline" onClick={() => { setEditing(null); setName(''); }}>Cancel</button>}</div>{save.isError && <p className="form-error">{apiMessage(save.error)}</p>}</form>{services.isLoading ? <div className="empty-state">Loading services…</div> : <><ResponsiveTable columns={['Service', 'Active', 'Added', 'Actions']} rows={serviceItems.slice((servicePage-1)*8,servicePage*8).map((item) => [item.name, item.active ? 'Yes' : 'No', formatDate(item.createdAt), <div className="button-row" key={item._id}><button type="button" className="button button-outline table-action" onClick={() => edit(item)}><Pencil size={15}/> Edit</button><button type="button" className="button danger-button table-action" onClick={() => window.confirm(`Delete ${item.name}?`) && remove.mutate(item._id)}><Trash2 size={15}/> Delete</button></div>])} empty="No legal services are configured."/><Pagination page={servicePage} pages={servicePages} total={serviceItems.length} onChange={setServicePage} label="legal services"/></>}</section><section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Customer requests</span><h2>Legal service enquiries</h2></div></div>{requests.isLoading ? <div className="empty-state">Loading requests…</div> : requests.isError ? <p className="form-error">{apiMessage(requests.error)}</p> : <><ResponsiveTable columns={['Name', 'Phone', 'Email', 'Service', 'Received', 'Status']} rows={requestItems.slice((requestPage-1)*8,requestPage*8).map((item) => [item.name, item.phone, item.email || '—', item.serviceName, formatDate(item.createdAt), item.status])} empty="No legal service requests yet."/><Pagination page={requestPage} pages={requestPages} total={requestItems.length} onChange={setRequestPage} label="legal enquiries"/></>}</section></DashboardShell>;
}
