import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Eye, FileCheck2, ListFilter, Search, Trash2, Workflow, X } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { DashboardTabs, Pagination } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate, humanize } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

const statuses = ['submitted', 'new', 'contacted', 'documents_pending', 'documents_received', 'under_internal_review', 'additional_information_required', 'submitted_to_provider', 'under_provider_review', 'approved', 'rejected', 'disbursed_or_policy_issued', 'closed', 'cancelled'];
const pageSize = 8;

export function AdminApplicationsPage() {
  const queryClient = useQueryClient(); const [active, setActive] = useState('list'); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState(null); const [checked, setChecked] = useState([]); const [page, setPage] = useState(1);
  const applications = useQuery({ queryKey: ['admin-applications', search, status, page], enabled: active === 'list', queryFn: async () => (await api.get('/dashboard/admin/applications', { params: { q: search, status, page, limit: pageSize } })).data });
  const remove = useMutation({ mutationFn: ({ ids, reason }) => api.delete('/dashboard/admin/records', { data: { type: 'applications', ids, reason } }), onSuccess: () => { setChecked([]); return Promise.all([queryClient.invalidateQueries({ queryKey: ['admin-applications'] }), queryClient.invalidateQueries({ queryKey: ['dashboard', 'admin'] })]); } });
  const tabs = [{ id: 'list', label: 'All tracking orders', icon: ListFilter, count: applications.data?.meta?.total }, { id: 'manage', label: 'Update selected', icon: Workflow, count: selected ? 1 : 0 }];
  function openApplication(id) { setSelected(id); setActive('manage'); }
  function closeApplication() { setSelected(null); setActive('list'); }
  function toggle(id) { setChecked((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function toggleAll(ids) { setChecked((current) => ids.every((id) => current.includes(id)) ? current.filter((id) => !ids.includes(id)) : [...new Set([...current, ...ids])]); }
  function confirmDelete() { if (!checked.length) return; const reason = window.prompt(`Reason for deleting ${checked.length} selected applications?`); if (!reason || reason.trim().length < 3) return; if (window.confirm(`Delete ${checked.length} selected applications and their status history? This cannot be undone.`)) remove.mutate({ ids: checked, reason: reason.trim() }); }
  return <DashboardShell role="admin" title="Tracking Orders"><section className="dashboard-welcome"><div><span className="eyebrow">Customer application tracking</span><h1>Track customer applications.</h1><p>Open a Customer application and publish each stage. The Customer sees the status and public note immediately in their dashboard.</p></div><FileCheck2/></section><DashboardTabs tabs={tabs} active={active} onChange={setActive} label="Tracking order sections"/>
    {active === 'list' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="dashboard-filters"><label><Search/><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Application ID, lead ID, customer name, mobile"/></label><select aria-label="Filter tracking orders by status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map((item) => <option value={item} key={item}>{humanize(item)}</option>)}</select></div>{applications.isLoading ? <div className="empty-state">Loading tracking orders…</div> : applications.isError ? <p className="form-error">{apiMessage(applications.error)}</p> : <>{checked.length > 0 && <div className="selection-toolbar"><strong>{checked.length} tracking orders selected</strong><button type="button" className="button danger-button" onClick={confirmDelete} disabled={remove.isPending}><Trash2 size={16}/>{remove.isPending ? 'Deleting…' : 'Delete selected'}</button></div>}{remove.isError && <p className="form-error">{apiMessage(remove.error)}</p>}<ResponsiveTable columns={['Tracking ID', 'Customer', 'Service', 'Requested', 'Submitted', 'Stage', 'Action']} rows={(applications.data?.data || []).map((item) => [item.applicationId, <span key="person">{item.personal?.fullName}<small>{item.personal?.mobile}</small></span>, item.service?.name || '—', item.financial?.requestedAmount ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(item.financial.requestedAmount) : '—', formatDate(item.submittedAt), humanize(item.status), <button key="open" className="table-link text-button" onClick={() => openApplication(item._id)}>Open tracking</button>])} empty="No Customer tracking orders match the filters." selection={{ ids: (applications.data?.data || []).map((item) => item._id), selected: checked, label: 'tracking order', toggle, toggleAll }}/><Pagination page={page} pages={applications.data?.meta?.pages} total={applications.data?.meta?.total} onChange={setPage} label="tracking orders"/></>}</section>}
    {active === 'manage' && (selected ? <ApplicationDetail id={selected} onClose={closeApplication}/> : <section className="dashboard-card dashboard-section tab-panel empty-state" role="tabpanel"><FileCheck2/><h2>No tracking order selected</h2><p>Open “All tracking orders” and choose a Customer application.</p><button className="button button-gold" type="button" onClick={() => setActive('list')}>Choose a tracking order</button></section>)}
  </DashboardShell>;
}

function ApplicationDetail({ id, onClose }) {
  const queryClient = useQueryClient(); const detail = useQuery({ queryKey: ['admin-application', id], queryFn: async () => (await api.get(`/dashboard/admin/applications/${id}`)).data.data });
  const form = useForm({ defaultValues: { status: 'contacted', publicNote: '', internalNote: '', reason: '' } });
  const update = useMutation({ mutationFn: (values) => api.patch(`/dashboard/admin/applications/${id}/status`, values), onSuccess: () => { form.reset(); queryClient.invalidateQueries({ queryKey: ['admin-application', id] }); queryClient.invalidateQueries({ queryKey: ['admin-applications'] }); } });
  if (detail.isLoading) return <section className="dashboard-card dashboard-section tab-panel">Loading application detail…</section>;
  if (detail.isError) return <section className="dashboard-card dashboard-section tab-panel"><p className="form-error">{apiMessage(detail.error)}</p></section>;
  const data = detail.data; const application = data.application;
  return <section className="dashboard-card dashboard-section application-admin-detail tab-panel" role="tabpanel"><div className="card-heading"><div><span className="eyebrow">{application.applicationId}</span><h2>{application.personal?.fullName}</h2></div><button className="button button-outline" onClick={onClose}>Back to tracking orders</button></div><dl className="detail-list"><div><dt>Customer type</dt><dd>{data.customerType === 'nri' ? 'NRI Customer' : 'Indian Customer'}</dd></div><div><dt>Mobile</dt><dd>{application.personal?.mobile}</dd></div><div><dt>Email</dt><dd>{application.personal?.email}</dd></div><div><dt>Location</dt><dd>{[application.personal?.city, application.personal?.state, application.personal?.country, application.personal?.pinCode].filter(Boolean).join(', ')}</dd></div><div><dt>Service</dt><dd>{application.service?.name}</dd></div><div><dt>Status</dt><dd>{humanize(application.status)}</dd></div><div><dt>Employment</dt><dd>{humanize(application.financial?.employmentType)}</dd></div><div><dt>Requested amount</dt><dd>{formatCurrency(application.financial?.requestedAmount)}</dd></div><div><dt>Referral code</dt><dd>{application.referralCode || 'Direct'}</dd></div></dl>{data.customerType === 'nri' && <AdminNriDocuments applicationId={application._id} requirements={data.documentRequirements}/>}<div className="dashboard-columns"><article><h3>Status history</h3><ol className="admin-timeline">{data.history.map((item) => <li key={item._id}><strong>{humanize(item.newStatus)}</strong><p>{item.publicNote}</p><small>{formatDate(item.createdAt)}</small></li>)}</ol></article><form className="dashboard-form" onSubmit={form.handleSubmit((values) => update.mutate(values))}><h3>Publish status update</h3><label>New status<select {...form.register('status', { required: true })}>{statuses.map((item) => <option value={item} key={item}>{humanize(item)}</option>)}</select></label><label>Customer-visible note<textarea rows="3" {...form.register('publicNote', { required: true, minLength: 5 })}/></label><label>Internal note<textarea rows="2" {...form.register('internalNote')}/></label><Field label="Reason for change" register={form.register('reason', { required: true, minLength: 3 })}/><button className="button button-gold" disabled={update.isPending}>{update.isPending ? 'Updating…' : 'Update application status'}</button>{update.isError && <p className="form-error">{apiMessage(update.error)}</p>}</form></div></section>;
}

function AdminNriDocuments({ applicationId, requirements }) {
  const queryClient = useQueryClient();
  const review = useMutation({ mutationFn: ({ documentId, status, rejectionReason }) => api.patch(`/dashboard/admin/applications/${applicationId}/documents/${documentId}`, { status, ...(rejectionReason ? { rejectionReason } : {}) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin-application', applicationId] }) });
  function reject(documentId) { const reason = window.prompt('Tell the customer why this document must be uploaded again.'); if (reason?.trim().length >= 3) review.mutate({ documentId, status: 'rejected', rejectionReason: reason.trim() }); }
  const uploaded = requirements.filter((item) => item.document).length;
  return <section className="admin-nri-documents"><div className="card-heading"><div><span className="eyebrow">NRI documents</span><h3>{uploaded} of {requirements.length} uploaded</h3><p>Open each private document, then approve it or ask the customer to upload it again.</p></div><FileCheck2/></div><div className="admin-document-list">{requirements.map((item) => { const document = item.document; const status = !document ? 'Not uploaded' : document.status === 'verified' ? 'Approved' : document.status === 'rejected' ? 'Upload again requested' : 'Uploaded — awaiting review'; return <article key={item.key} className={document?.status || 'missing'}><div><strong>{item.label}</strong><span>{status}</span>{document?.originalName && <small>{document.originalName} · {formatFileSize(document.size)}</small>}{document?.rejectionReason && <p>{document.rejectionReason}</p>}</div>{document && <div className="button-row">{document.viewUrl && <a className="button button-outline table-action" href={document.viewUrl} target="_blank" rel="noreferrer"><Eye size={15}/> View</a>}{document.status === 'uploaded' && <><button type="button" className="button button-gold table-action" onClick={() => review.mutate({ documentId: document._id, status: 'verified' })} disabled={review.isPending}><Check size={15}/> Approve</button><button type="button" className="button danger-button table-action" onClick={() => reject(document._id)} disabled={review.isPending}><X size={15}/> Upload again</button></>}</div>}</article>; })}</div>{review.isError && <p className="form-error">{apiMessage(review.error)}</p>}</section>;
}
function formatCurrency(value) { return Number(value) > 0 ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value) : '—'; }
function formatFileSize(value) { return `${Math.max(1, Math.round(Number(value || 0) / 1024))} KB`; }
function Field({ label, register }) { return <label>{label}<input {...register}/></label>; }
